version: "3.8"

services:
    #Container MYSQL
    db:
        image: mysql
        container_name: docker_mysql
        restart: always
        volumes: 
            - db-data:/var/lib/mysql
        environment: 
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks: 
            - dev
    #Container PHPMYADMIN
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        container_name: docker_phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
        ports:
            - "8080:80"
        networks:
            - dev
            
    #APACHE + PHP 7.4 ON FOLDER PHP
    www:
        build: php
        container_name: docker_www
        ports:
            - 8082:80
        volumes: 
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev
networks: 
    dev:

volumes: 
    db-data: